### ISSUE TITLE
Organization名を考える

### ISSUE THREAD

**Issue by sota1235** [rawguy/board#1]
候補
- gckai
- mob-lab
- mob-dev

**Comment by nekobato** [comment]
mob-gc

**Comment by sota1235** [comment]
marutaru [8:57 PM]  
sotkai

[8:57]  
tintinkai

[8:57]  
oppaikai

ytanaka [8:57 PM]  
gcm

marutaru [8:57 PM]  
jkkai

[8:57]  
hartcatchkai

nekobato [8:59 PM]  
gcx

[9:01]  
ttxx

marutaru [9:01 PM]  
jkx

[9:01]  
jcx

takumibaba [9:02 PM]  
jsx

marutaru [9:02 PM]  
icup

nekobato [9:02 PM]  
gcup

keroxp [9:03 PM]  
mobio

[9:03]  
あった…

nekobato [9:03 PM]  
mobit

marutaru [9:03 PM]  
paipai

sota1235 [9:04 PM]  
garbage-collect

[9:04]  
logai

[9:04]  
rowgai

takumibaba [9:04 PM]  
rawguy空いてる

marutaru [9:04 PM]  
rowguy

nekobato [9:04 PM]  
rawguy

sota1235 [9:04 PM]  
rawguy

new messages
marutaru [9:04 PM]  
rawguy
